### ISSUE TITLE
Add-on documentation code background is white

### ISSUE THREAD

**Issue by leroyboerefijn** [home-assistant-community-themes/blue-night#13]
When viewing the documentation pages of add-ons in the supervisor add-on store, the background of example code blocks is white, while the text is light gray. This makes it very hard to read.

Please change this background color to some form of dark gray/black.

![image](https://user-images.githubusercontent.com/34075651/83754385-2d9a7f00-a66c-11ea-9773-51020dead490.png)

**Comment by maartenpaauw** [comment]
Thanks for submitting an issue. Feel free to send a PR! 😄

**Comment by ksya** [comment]
Someone knows (how to find) the variable for this?

**Comment by leroyboerefijn** [comment]
I had to do some digging, but found that the background color of these code blocks are specified with markdown-code-background-color (https://github.com/home-assistant/frontend/blob/dev/src/components/ha-markdown.ts).

I just tested it and created a PR (my first ever!)

**Comment by maartenpaauw** [comment]
@leroyboerefijn I've merged your PR. Thanks for taking time to contribute to open source projects!
