### ISSUE TITLE
Dropdown form input doesn't follow the theme

### ISSUE THREAD

**Issue by sdrapha** [home-assistant-community-themes/blue-night#29]
Currently, the new form input elements doesn't follow the theme

Current:
![Screenshot_20211210-232552_Brave](https://user-images.githubusercontent.com/25059996/145664133-31208c17-fc13-442c-a07d-b0457b381e39.jpg)

I'm already doing a pull request to fix that, but I'm posting an issue first to keep track of it.

Proposal:
![Screenshot_20211210-232455_Brave](https://user-images.githubusercontent.com/25059996/145664142-1c3515cf-a43d-40e4-ba76-31d4b4eb6e16.jpg)

**Comment by maartenpaauw** [comment]
Thank you!
